/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Headphones.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../contexts/Customization';

const Headphones = (props) => {
  const { HeadphoneCol } = useCustomization();
  const { nodes, materials } = useGLTF('./models/Headphones.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Headphones.geometry} material={materials.Mat}>
        <meshStandardMaterial color={HeadphoneCol.color}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/Headphones.gltf')

export default Headphones;
